In [2]:
import nibabel as nib
import numpy as np

ct_path = r"Z:\Angie\SMILE_facialdeformation\StJude_cohort\abby\1720903\Plan\1720903_plan_shifted.nii"
mandible_mask_path = r"Z:\Angie\SMILE_facialdeformation\StJude_cohort\abby\1720903\Plan\TotalSegmentator1\mandible.nii.gz"
mirror_axis = 0
out_prefix = "mirror"

ct_nib = nib.load(ct_path)
mask_nib = nib.load(mandible_mask_path)

print("CT shape:", ct_nib.shape)
print("CT affine:\n", ct_nib.affine)

def mirror_nib_image(img, axis=0):
    data = img.get_fdata()
    flipped = np.flip(data, axis=axis).copy()

    affine = img.affine.copy()
    dims = img.shape

    translation = affine[:3, axis] * (dims[axis] - 1)

    new_affine = affine.copy()
    new_affine[:3, axis] *= -1
    new_affine[:3, 3] = affine[:3, 3] + translation

    return nib.Nifti1Image(flipped, new_affine, img.header)

ct_mirrored = mirror_nib_image(ct_nib, axis=mirror_axis)
mask_mirrored = mirror_nib_image(mask_nib, axis=mirror_axis)

ct_mirrored_path = out_prefix + "_ct.nii.gz"
mask_mirrored_path = out_prefix + "_mandible.nii.gz"

nib.save(ct_mirrored, ct_mirrored_path)
nib.save(mask_mirrored, mask_mirrored_path)

print("Saved:", ct_mirrored_path)
print("Saved:", mask_mirrored_path)


CT shape: (512, 512, 179)
CT affine:
 [[-8.12492371e-01  0.00000000e+00 -0.00000000e+00  2.07589996e+02]
 [ 0.00000000e+00 -8.12492371e-01 -1.69007988e-10  4.63939972e+02]
 [ 0.00000000e+00  6.86585927e-11 -2.00000763e+00 -4.13500000e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Saved: mirror_ct.nii.gz
Saved: mirror_mandible.nii.gz
